server:
  port: 9090

spring:
  application:
    name: AUTH
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    profiles:
      active: default
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: 1234
    baseline-description: "init"
    baseline-version: 0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437u
  expiration-time: 86400 # 24 часа в секундах

logging:
  level:
    root: info
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30