spring:
  application:
    name: AUTH
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    profiles:
      active: default


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    registry-fetch-interval-seconds: 60
    initial-instance-info-replication-interval-seconds: 60
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true

server:
  port: 9090

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437u
  expiration-time: 86400 # 24 часа в секундах

