spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**

        - id: task-management
          uri: lb://TASK-MANAGEMENT
          predicates:
            - Path=/api/v1/tasks/**
          filters:
            - AuthenticationFilter

        - id: statistic
          uri: lb://STATISTIC
          predicates:
            - Path=/api/v1/statistic/**
          filters:
            - AuthenticationFilter


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 9091

logging:
  level:
    root: INFO
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

