server:
  port: 9095

spring:
  application:
    name: TASK-STATISTIC
  datasource:
    url: jdbc:postgresql://localhost:5432/statistic_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    profiles:
      active: default
  kafka:
    topic:
      task-created: task_created
      task-updated: task_updated
      task-deleted: task_deleted

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
